### ISSUE TITLE
IndexOutOfBoundsException (api 7)

### ISSUE THREAD

**Issue by ziceptor** [SimonFlash/ActiveTime#4]
After starting the server in console https://gist.github.com/ziceptor/f28685faa03ae722bd2074b81b5b389b

**Comment by SimonFlash** [comment]
Fixed this bug in [[v1.2.2]](https://github.com/SimonFlash/ActiveTime/releases/tag/v1.2.2). I believe this was related to having empty data logs.

**Comment by ziceptor** [comment]
After updating https://gist.github.com/ziceptor/7dc13020ecf0e2563e5e4dcb51321bf1

**Comment by SimonFlash** [comment]
This is my bad. I haven't been able to test things properly. [[v1.2.3]](https://github.com/SimonFlash/ActiveTime/releases/tag/v1.2.3)

**Comment by ziceptor** [comment]
After updating https://gist.github.com/ziceptor/74d04441346b13f12f6a3867f3832309

**Comment by SimonFlash** [comment]
That seems to be Nucleus related - potentially a version difference between API 6 and API 7, but I don't know enough to say. I'll see what I can find out.
