### ISSUE TITLE
NoSuchMethodError

### ISSUE THREAD

**Issue by ziceptor** [SimonFlash/ActiveTime#6]
forge-1.12.2-14.23.0.2486-universal.jar
spongeforge-1.12.2-2486-7.0.0-BETA-2645.jar
ActiveTime-s6.0-v1.2.4.jar

https://gist.github.com/ziceptor/8eaab3e1781019c02c292ed374a62015

**Comment by SimonFlash** [comment]
This is a Sponge incompatibility error. An API 7 version of ActiveTime will not be released until there is a stable API version of Sponge.

**Comment by ziceptor** [comment]
Sad! The availability of plug-ins for the experimental version of the sponge gives more testers for the project. The benefits are obvious. There are negative aspects for plugin developers. I hope you find the time :) Thank you for your work!
