### ISSUE TITLE
1.12.2 Won't work anything

### ISSUE THREAD

**Issue by Krosta8** [SimonFlash/ActiveTime#7]
Hello
I know, that this plugin is on Sponge API 6.0.0, but I just want to let you know about the issue and I hope, that you maybe consider update it to Sponge API 7.0.0 😄 

I tried to run commads and no one works.
Everytime error: https://pastebin.com/sEnem0zj

I'm using Sponge 1.12.2 and Forge 2491

**Comment by SimonFlash** [comment]
Please see [Issue 3](https://github.com/SimonFlash/ActiveTime/issues/3) and [Issue 6](
https://github.com/SimonFlash/ActiveTime/issues/6).
