### ISSUE TITLE
Updating from older version doesnt carry over data

### ISSUE THREAD

**Issue by Dpa1991** [SimonFlash/ActiveTime#8]
I've been on 1.0.4 because I thought all later versions only ran on sponge api 6.0 until specified by the most recent build which says it runs on sponge 5.x

Unfortunately upon updating my players data don't carry over. Is there a way you can import the data via a command or am I just out of luck? I tried updating to various versions to see if some slightly older ones would migrate the data but no luck.

**Comment by SimonFlash** [comment]
Unfortunately, there isn't much I can do about it - builds have already passed through and the configuration doesn't save data in the same way. I still might be able to manually do a conversion, so if that's something you still need feel free to send me a gist of your storage file and I'll see what I can do.
